# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshAgentMultiplexer < Formula
  desc "ssh-agent-multiplexer: a small program which multiplexes running ssh agents"
  homepage "https://github.com/everpeace/ssh-agent-multiplexer"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.5.0/ssh-agent-multiplexer_0.5.0_darwin_amd64.tar.gz"
      sha256 "ea7f1a7627ea0c382c7b6816ed1b3d534e4bdf86de5464720fe43185f30d7664"

      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.5.0/ssh-agent-multiplexer_0.5.0_darwin_arm64.tar.gz"
      sha256 "1a47d3081dc2086d449729b657a2214e75f36b16f41369c40eefc35fb67b7692"

      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.5.0/ssh-agent-multiplexer_0.5.0_linux_amd64.tar.gz"
      sha256 "c9b12e7961face9b308fb40f190c0519739dbfdef12ecdd44d9745cbc7d666eb"
      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.5.0/ssh-agent-multiplexer_0.5.0_linux_arm64.tar.gz"
      sha256 "c52bef95843b6ed553d311ca611a96f1472f850f67c7169b1d081f353fadfb68"
      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
  end

  service do
    run opt_bin/"ssh-agent-multiplexer"
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/ssh-agent-multiplexer.log"
    error_log_path var/"log/ssh-agent-multiplexer.log"
  end
end
