# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshAgentMultiplexer < Formula
  desc "ssh-agent-multiplexer: a small program which multiplexes running ssh agents"
  homepage "https://github.com/everpeace/ssh-agent-multiplexer"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.3.1/ssh-agent-multiplexer_0.3.1_darwin_amd64.tar.gz"
      sha256 "ab4b8df5991b7c73af3c628d239f608bf64f5073850d836205d64e9e16bef3a6"

      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.3.1/ssh-agent-multiplexer_0.3.1_darwin_arm64.tar.gz"
      sha256 "5339d4c992247805f9dc11ff66d1e08d56f604727eff94ac3a9b8ca8c754cbbb"

      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.3.1/ssh-agent-multiplexer_0.3.1_linux_amd64.tar.gz"
      sha256 "3c57a236ed6a61feed5f12e1f75e8266b4e326b3a35c52d1c2f55fcf0fc71d69"
      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.3.1/ssh-agent-multiplexer_0.3.1_linux_arm64.tar.gz"
      sha256 "edb3b99a2efa81a9ae0d8307337359d798e119535968b2be258e852520a744f6"
      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
  end

  service do
    run opt_bin/"ssh-agent-multiplexer"
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/ssh-agent-multiplexer.log"
    error_log_path var/"log/ssh-agent-multiplexer.log"
  end
end
