# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshAgentMultiplexer < Formula
  desc "ssh-agent-multiplexer: a small program which multiplexes running ssh agents"
  homepage "https://github.com/everpeace/ssh-agent-multiplexer"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.4.0/ssh-agent-multiplexer_0.4.0_darwin_amd64.tar.gz"
      sha256 "c31064ff9691668cd8bf1efdf4e67ad78274156aaff5c927f7686c5b7de41c8a"

      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.4.0/ssh-agent-multiplexer_0.4.0_darwin_arm64.tar.gz"
      sha256 "8a92af3bc923f403641094f466f9b3bee4631e8d016535922255ec9fffc32908"

      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.4.0/ssh-agent-multiplexer_0.4.0_linux_amd64.tar.gz"
      sha256 "326c949b09578cdaf05334446f99444e20522b2faa2f2478a07e1aac79f3af0f"
      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/everpeace/ssh-agent-multiplexer/releases/download/v0.4.0/ssh-agent-multiplexer_0.4.0_linux_arm64.tar.gz"
      sha256 "915e3581a5932f03371b29efd25551ff76cc7d1f316351835716c67688533148"
      def install
        bin.install "ssh-agent-multiplexer"
        bin.install "ssh-agent-mux-select"
      end
    end
  end

  service do
    run opt_bin/"ssh-agent-multiplexer"
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/ssh-agent-multiplexer.log"
    error_log_path var/"log/ssh-agent-multiplexer.log"
  end
end
